version: "3"

services:
  go:
    container_name: koukaten2022_GO
    build:
      context: ./docker/go
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    # env_file:
    #   - ./Docker/go/.env
    volumes:
      - ./go:/go/src/app # マウントディレクトリ
    ports:
      - 8080:8080
    depends_on:
      - "neo4j"

  neo4j:
    container_name: koukaten2022_NEO4J
    image: neo4j
    restart: always
    extra_hosts: # 追加
      - localhost:172.18.0.1 # 追加
    ports:
      - 57474:7474
      - 57687:7687
    volumes:
      - ./volumes/neo4j/data:/data
